-- AlterTable. Added nullable, backfilled, then tightened: `@default(nanoid(8))`
-- is generated by Prisma on insert and never reaches Postgres, so an existing
-- row has nothing to fall back on and `ADD COLUMN ... NOT NULL` would fail.
ALTER TABLE "User" ADD COLUMN     "studyId" TEXT;

-- Backfill: same shape as the nanoid the client will generate from now on —
-- 8 random hex characters, unique in practice at study scale, and the unique
-- index below is what actually proves it.
UPDATE "User" SET "studyId" = substr(replace(gen_random_uuid()::text, '-', ''), 1, 8) WHERE "studyId" IS NULL;

ALTER TABLE "User" ALTER COLUMN "studyId" SET NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "User_studyId_key" ON "User"("studyId");
